version: '3.8'

services:

  server:
    image: flexify-server:latest
    container_name: flexify-server
    ports:
      - "9501:8080"
    environment:
      DB_HOST: localhost:5432
      DB_USER: root_user
      DB_PASSWORD: root_password

  web:
    image: flexify-web:latest
    container_name: flexify-web
    ports:
      - "9301:3000"
    environment:
      BACKEND_HOST: http://flexify-server:8080
